pages/tx/[hash].tsx
The gas price returned from API has been formatted and can
be displayed directly
Ref: https://github.com/nervosnet/godwoken_explorer/issues/361
=> fix: remove redundant format on gas price

utils/api/tx.ts
Change default value of polyjuice status from 'pending' to
'succeed' since 'pending' will be returned explicitly but
null will be returned if tx is not of type polyjuice. In
this case the polyjuice status could be ignored or regarded
as succeed.
Ref: https://github.com/nervosnet/godwoken_explorer/issues/389
=> fix: set polyjuice status default to be 'succeed'

components/ERC20TransferList.tsx, components/SimpleERC20TransferList.tsx, utils/api/txs.ts
`item.hash + item.from + item.to` cannot differentiate erc20 transfers because multiple erc20 transfers can be included in a single transaction and send from/to the same addresses, thus they share the same `item.hash + item.from + item.to`, adding `log_index` to differentiate them.
=> fix: add log index to index transfer records

utils/constants.ts
Reverts Magickbase/godwoken-explorer-ui#182
This commit misunderstood the design of CKB in godwoken.
There are two kinds of `CKB` in fact.
The one deposited from layer1 and minted as layer2 bridged token `CKB`, has decimal 8.
The other one is used as transaction fee in layer2 transaction, named `gCKB`, has decimal 18.
`CKB_DECIMAL` is used with `CKB` but not `gCKB`, so it should be intact.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/529
=> Revert "feat: set ckb decimal 18"

pages/tx/[hash].tsx
Ref: https://github.com/Magickbase/godwoken_explorer/issues/549#issuecomment-1139225837
Before:
After:
=> fix: hide contract address if its length is incorrect

pages/charts.tsx
=> fix: add unit in tooltips of charts

components/BridgedRecordList.tsx, public/locales/en-US/list.json, public/locales/zh-CN/list.json, utils/api/bridged.ts
This PR adds a `fast withdrawal` icon before bridge records that transfer assets from godwoken v0 to godwoken v1 by `fast-withdraw`
Ref: https://github.com/Magickbase/godwoken_explorer/issues/553
=> feat: mark fast withdrawal

components/DownloadMenu/index.tsx, pages/account/[id].tsx, pages/block/[id].tsx, pages/token/[id].tsx, pages/tx/[hash].tsx, public/locales/en-US/common.json, public/locales/zh-CN/common.json
1. export tx list, transfer list, bridged record list in account page
2. export tx list, bridged record list in block page
3. export transfer list, bridged record list, holder list in token page
4. export transfer list in tx page
https://user-images.githubusercontent.com/7271329/176503022-7e18386f-9132-4630-8d2c-7b47b35f4b02.mov
=> feat: add export data button in some pages

components/AccountOverview.tsx, components/BridgedRecordList.tsx, components/TxList.tsx, pages/contracts.tsx, pages/tx/[hash].tsx, pages/txs.tsx, utils/constants.ts
pCKB is a special token(default token) so users are all clear
that it's bridged from ckb via force bridge. So in label and
table header it can be simplified as pCKB instead of pCKB.gw|fb.eth
Ref: https://github.com/Magickbase/godwoken_explorer/issues/772
---
1. account detail(balance)
2. bridged token list (deposited with pCKB)
3. tx detail(value, price, fee)
4. tx list(value)
5. contract list(balance)
=> feat: use pCKB instead of pCKB.gw|fb.eth in label and table header

components/ContractInfo/styles.module.scss
color of text field in contract page should be #333 but not #999
Ref: https://github.com/Magickbase/godwoken_explorer/issues/862
=> fix: fix color of text field in contract page

components/ContractEventsList.tsx
Preview: https://godwoken-explorer-ui-git-fix-color-of-tx-hash-5f09ff-nervosnet.vercel.app/account/0x96c5f1e50c4393efa890699cd9aecf3fb58dcb99?tab=events
Ref: https://github.com/Magickbase/godwoken_explorer/issues/862
=> fix: fix color of links in events of a contract account

components/AccountOverview/styles.module.scss, components/AssetList/index.tsx, components/RoundedAmount.tsx, pages/token/styles.module.scss, pages/tx/styles.module.scss
1. set font weight of amount outside list to 400
2. update style of amount in user asset list
Left: after, right: before
Ref: https://github.com/Magickbase/godwoken-explorer-ui/issues/477
=> feat: update amount style

components/TokenApprovalList/RevokeButton.tsx, components/TokenApprovalList/index.tsx, components/TokenApprovalList/styles.module.scss, public/locales/en-US/list.json, public/locales/zh-CN/list.json, utils/helpers.ts
resolves https://github.com/Magickbase/godwoken_explorer/issues/1027, resolves https://github.com/Magickbase/godwoken_explorer/issues/1011
Gaps after revoke txn is sent out:
txn sent   ------gap1----->   txn being put in a block   ------gap2----->   backend sync and update data
This implementation shows the button's loading state only during gap1, and then hide the revoking item during gap2.  @Keith-CY  @FrederLu 
https://user-images.githubusercontent.com/32790369/193224872-556a4302-51b2-4532-a391-e7e58911f0cf.mov
=> feat: token revoke txn loading

components/TxList/index.tsx, components/TxList/styles.module.scss, cypress/integration/block/index.spec.ts
This PR marks `Send` as the default `method name` for a `native transfer` transaction
Styles after and before update
Ref: https://github.com/Magickbase/godwoken_explorer/issues/999
=> feat: mark native transfer's method as 'Send'

components/NFTActivityList/index.tsx, components/SimpleERC20Transferlist/index.tsx, pages/token/[id].tsx
This PR is for fixing the cropped tooltip in NFT pages and the issue of the tooltip in the `method` column.
Before:
After:
Ref:https://github.com/Magickbase/godwoken_explorer/issues/1094
=> Fix:Tooltip in NFT pages is cropped

components/Polyjuice.tsx
Fix the issue when we hover the L2 script hash there is not a tooltip.
Before: 
After:
Ref:https://github.com/Magickbase/godwoken_explorer/issues/1084
=> fix: The L2 Script Hash on the Polyjuice Creator Account page is displayed abnormally.

components/MultiTokenActivityList/index.tsx, components/MultiTokenInventoryList/index.tsx, pages/multi-token-item/[...id].tsx
------
Each token item of ERC 721/1155 could have its own metadata, as https://v1.testnet.gwscan.com/nft-item/0x784cd3c52813098763c371df8fbe8ed27d2c1ebd/1339?tab=metadata
Now the metadata is fetched from front-end directly so the name and cover of a token item appear slowly.
Issue https://github.com/Magickbase/godwoken_explorer/issues/967 requires a new field metadata to be returned within the API so we can avoid requests in the front-end to deliver info smoothly.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1108
Check List
------
This PR mainly focuses on replacing the APIs used in the `multi-token-collections`.
e2e Test
none
=> Fix: Read metadata of ERC 721/1155 from backend API

components/AccountOverview/index.tsx, components/AccountOverview/styles.module.scss, components/SmartContractInfo/index.tsx, pages/token/[id].tsx, pages/token/styles.module.scss
------
There is a common problem in the page `account` and the page `Token`, when our page is a two-column layout, adaptive layout makes the first column wider. 
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1111
Check List
------
e2e Test
none
=> Fix: wrapped label and the basic info width

pages/token/[id].tsx, pages/token/styles.module.scss
fix https://github.com/Magickbase/godwoken_explorer/issues/1171
Add translation for import token button's title attribute:
=> fix: i18n for import token title

components/ERC20TransferList/index.tsx
closes https://github.com/Magickbase/godwoken_explorer/issues/1224
increase transfer list value column width, so other table columns won't shift too much
https://user-images.githubusercontent.com/32790369/208227266-7bb9cf79-bc03-4292-b1a4-e94878581587.mov
=> fix: transfer list value column width

components/Tooltip.tsx
closes https://github.com/Magickbase/godwoken_explorer/issues/1219
Try to make sure material-ui tooltip shows on mobile:
https://user-images.githubusercontent.com/32790369/208227475-b5c2b6f5-d826-4553-b68a-f953900abb4e.mov
=> fix: tooltip not shown on mobile

cypress/integration/txs/pendingTxs.spec.ts, package-lock.json, package.json
1. i18next is required by next-i18next
2. disable tests of pending transactions because the list
is empty randomly
=> fix: fix missing dep and test case

components/AccountOverview/index.tsx, pages/account/[id].tsx
------
The account subfield is affected by PR https://github.com/Magickbase/godwoken_explorer/pull/1241, and the graphql query should be updated accordingly.
I updated the request for `account`.
Expect: 
The `Basic Info` will display normally.
Ref: 
https://github.com/Magickbase/godwoken_explorer/pull/1241
https://github.com/Magickbase/godwoken_explorer/issues/1246
Check List
------
e2e Test
none
=> Fix: Update account api for new type declaration

.github/workflows/test.e2e.yml, components/AccountOverview/index.tsx, cypress/integration/search/index.spec.ts, pages/account/[id].tsx, pages/search-result-tokens/index.tsx, pages/search-result-tokens/styles.module.scss, pages/token/[id].tsx, public/locales/en-US/list.json, public/locales/zh-CN/list.json, utils/api/search.ts, utils/handler.ts
resolves https://github.com/Magickbase/godwoken_explorer/issues/1237, resolves https://github.com/Magickbase/godwoken_explorer/issues/1232
- replace search api to graphql
- add a new search result page for tokens:
https://user-images.githubusercontent.com/32790369/209527603-ca427e6a-7940-4132-b5b5-91588716697e.mov
=> feat: add search result tokens page

pages/token/styles.module.scss
fix https://github.com/Magickbase/godwoken_explorer/issues/1259
text is being clipped:
fix:
=> fix: text being clipped

pages/index.tsx
------
Before:
After:
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1278
Check List
------
e2e Test
none
=> Fix: Alignment of addresses in transaction list is weird

components/DownloadMenu/styles.module.scss, components/SmartContractInfo/index.tsx, components/SmartContractInfo/styles.module.scss, pages/index.module.scss, pages/index.tsx, pages/token/[id].tsx, pages/token/styles.module.scss, styles/tooltip.scss
1. make text unwrapped if it consists of several words
2. align tooltip to right border for mobile layout
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1199
---
1. Homepage: https://godwoken-explorer-ui-git-short-tooltip-unwrapped-magickbase.vercel.app/
Before
After
2. Account page: https://godwoken-explorer-ui-git-short-tooltip-unwrapped-magickbase.vercel.app/account/0xbe65f55eab96cc2a64e7b509421900b62c15e0c6
Before
After
3. Token page: https://godwoken-explorer-ui-git-short-tooltip-unwrapped-magickbase.vercel.app/token/375
Before
After
=> feat: optimize style of tooltip

cypress/integration/tx/index.spec.ts, pages/tx/[hash].tsx, pages/tx/styles.module.scss
resolve https://github.com/Magickbase/godwoken_explorer/issues/1296
tx page:
- display `Gas Price` decimal place like `Fee`
- align `Max Priority Fee Per Gas` and `Max Fee Per Gas`
- `Max Fee Per Gas` `Max Priority Fee Per Gas` `Call Gas Limit` `Verification Gas Limit` `Paymaster Data` show number 
- mobile responsive hash display
=> fix: tx page ui improvements

components/AccountOverview/index.tsx, pages/account/[id].tsx, pages/account/styles.module.scss, public/locales/en-US/account.json, public/locales/zh-CN/account.json
------
When we search for an account with the wrong eth address and the page is also on the page `account`, we will get a warning tip.
Figma: https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9158%3A32271&t=9cVjv7wlAYVixl66-1
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1225
Check List
------
e2e Test
none
=> Fix: Wrong format eth address also display page 

components/ContractInfo/index.tsx, public/locales/en-US/account.json, public/locales/zh-CN/account.json
This PR adds an `pCKB` field to specify the `pCKB` sent along with a transaction when the method of a contract is marked as `payable`
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1324
=> feat: add an amount field to specify pCKB sent along with a tx

components/AddressWithDomain/index.tsx, components/AddressWithDomain/styles.module.scss, components/MultiTokenActivityList/index.tsx, components/MultiTokenHolderList/index.tsx, components/MultiTokenHolderList/styles.module.scss, components/MultiTokenInventoryList/index.tsx, components/NFTActivityList/index.tsx, components/NFTHolderList/index.tsx, components/NFTHolderList/styles.module.scss, components/NFTInventoryList/index.tsx, components/NFTInventoryList/styles.module.scss, components/TitleWithDomain/index.tsx, components/TitleWithDomain/styles.module.scss, components/TruncatedAddress.tsx, components/TxList/index.tsx, package-lock.json, package.json, pages/index.tsx, pages/multi-token-item/[...id].tsx, pages/nft-item/[...id].tsx, pages/nft-item/styles.module.scss, pages/tx/[hash].tsx, utils/api/search.ts, utils/constants.ts, utils/graphql.ts, utils/handler.ts
------
1-1、 support searching ends with `.bit`
1-2、the .bit domain tag on the account page should be a `link` to .bit account page
2-1、 showing magickbase.bit on hovering .bit icon is redundant, now showing text `.bit Name`
3-1、 token/holder list, magickbase.bit is not displayed ( `not include in this PR`)
https://v1.gwscan.com/token/133?tab=holders&id=133&page=13
3-2、 nft-collection, in the inventory, owner is not displayed by .bit name https://v1.gwscan.com/nft-collection/0x73c0e2a4b765ed81f63759d1fcf2c4dcd2925f4a?tab=inventory
3-3、nft-item, owner is not displayed with .bit name
https://v1.gwscan.com/nft-item/0x73c0e2a4b765ed81f63759d1fcf2c4dcd2925f4a/2375
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1170
Check List
------
e2e Test
none
=> Fix:update .bit name in nft-collection and bridge token

cypress/integration/tokens/index.spec.ts, pages/nft-collections/index.tsx, pages/nft-collections/styles.module.scss, utils/handler.ts
------
This PR is for the page of `NFT-collections`.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/556
Check List
------
1、sorted by total supply/circulating supply
2、sorted by holders
3、sorted by name
4、filtered by name (fuzzy)
e2e Test
none
=> Feat: change the pagination to cursor and add sorter --- NFT collections

components/ErrorBoundary.tsx, components/FilterMenu/AgeFilterMenu.tsx, components/MultiTokenInventoryList/index.tsx, components/NFTActivityList/index.tsx, components/PageTitle/index.tsx, package-lock.json, package.json, pages/nft-collections/index.tsx
------
As title.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1351
Check List
------
e2e Test
none
=> fix:page display account is undefined

components/ContractInfo/index.tsx
This commit fixes the source code list by filtering files those not ending with .sol, so only solidity files will be displayed
Before: 
After:
Contract address on testnet: 0xf8f6173ae4a352de056e278ebc940af972b71de9
=> fix: filter metadata files out of source code

styles/tooltip.scss
------
As title.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1428
Check List
------
1、List
2、Detail
e2e Test
none
=> fix:layout of tooltip is improper

components/ContractInfo/index.tsx
string will be encoded/decoded with ',' if argument/response type is an array
Preview: https://godwoken-explorer-ui-git-fix-complex-argument-ae0f82-magickbase.vercel.app/account/0x309c15a655f8f1ab860f3ad81a233e8bcadb300e?tab=contract
Try: 
`["0x309c15a655f8f1ab860f3ad81a233e8bcadb300e","0x309c15a655f8f1ab860f3ad81a233e8bcadb300e"]`
or
`0x309c15a655f8f1ab860f3ad81a233e8bcadb300e,0x309c15a655f8f1ab860f3ad81a233e8bcadb300e`
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1421
=> fix: support complex arguments/response in contract call
