components/AssetList.tsx, components/SUDT.tsx, components/Search/index.tsx, components/SmartContract.tsx, components/User.tsx, cypress/integration/account/sudt.spec.ts, pages/account/[id].tsx
1. search with lowercase query string
2. adjust layout to display full hashes
=> Search with lowercase query string and adjust layout for full hashes

components/AssetList.tsx, components/SUDT.tsx, components/Search/index.tsx, components/SmartContract.tsx, components/User.tsx, cypress/integration/account/sudt.spec.ts, cypress/integration/home/index.spec.ts, pages/account/[id].tsx, pages/index.tsx
1. transform search string into lowercases
2. adjust the layout to display hashes and addresses more friendly
=> Deploy to mainnet

cypress/integration/account/index.spec.ts, cypress/integration/home/index.spec.ts, next-env.d.ts, package-lock.json, pages/404.tsx, pages/account/[id].tsx, pages/block/[id].tsx, pages/index.tsx, pages/tx/[hash].tsx, pages/txs.tsx, public/locales/en-US/statistic.json, public/locales/zh-CN/statistic.json, utils/handler.ts
1. update blocks in stats
2. fix message in 404
=> Release to mainnet

components/TxList.tsx, pages/index.tsx, pages/tx/[hash].tsx
1. remove polyjuice status
2. format polyjuice creator label of tx type
=> fix: fix tx list of meta account

pages/tokens/[type].tsx, utils/convertors.ts
1. fix format of token supply
2. use bignumber.js to format bigint instead of a method
self-implemented
=> fix: fix format of token supply

components/ContractInfo.tsx, pages/_app.tsx
1. add progress bar beneathe the header on navigating
2. add circulating loading in button on calling contract methods
https://user-images.githubusercontent.com/7271329/163011131-a5717db1-baaf-4b67-aa40-7a382c6a4dc4.mov
=> feat: add more loading animations

utils/api/utils.ts, utils/exceptions.ts
To fix https://github.com/nervosnet/godwoken_explorer/issues/348
When gw_hash is used to visit the page, an error will be displayed and ask users to use eth hash
=> feat: disable gw hash and indicate users to use eth hash

components/BridgedRecordList.tsx, utils/api/bridged.ts
Ref: https://github.com/Magickbase/godwoken_explorer/issues/178
=> feat: add ckb capacity in deposit/withdrawal record

pages/tx/[hash].tsx, public/locales/en-US/tx.json, public/locales/zh-CN/tx.json, utils/api/tx.ts
=> feat: add deployed contract in tx page

components/SmartContract.tsx, pages/account/[id].tsx, public/locales/en-US/account.json, public/locales/zh-CN/account.json, utils/api/account.ts, utils/api/utils.ts
Ref: https://github.com/Magickbase/godwoken_explorer/issues/243
=> feat: add deployer in tx page

pages/account/[id].tsx, pages/block/[id].tsx, pages/token/[id].tsx, pages/tx/[hash].tsx
fixes: [#357](https://github.com/Magickbase/godwoken_explorer/issues/357)
=> fix: disable scroll on push

pages/blocks.tsx, pages/charts.tsx
fixes: [489](https://github.com/Magickbase/godwoken_explorer/issues/489), [477](https://github.com/Magickbase/godwoken_explorer/issues/477)
=> fix: brush and block page next button

.gitignore, components/Head.tsx, package-lock.json, package.json, pages/_app.tsx
fixes: [#128](https://github.com/Magickbase/godwoken-explorer-ui/issues/128)
=> refactor: use self hosted fonts

components/UdtList.tsx, pages/account/[id].tsx, public/locales/en-US/account.json, utils/convertors.ts
1. get udt list by graphql
2. remove count of udt items in tab because other tabs have no count
3. add a link to token page in item of account udt list
Preview: https://godwoken-explorer-bcjs3twcv-nervosnet.vercel.app/account/0x23333496565720d945784a35aa655471493c0641?tab=assets
=> refactor: get udt list by graphql api

components/Header.tsx, pages/index.tsx, utils/api/index.ts, utils/api/info.ts, utils/constants.ts
=> feat: fetch godwoken version instead of using env

components/SimpleERC20TransferList.tsx, components/SimplePagination.tsx, components/TxList.tsx, pages/account/[id].tsx, pages/block/[id].tsx, pages/tx/[hash].tsx, public/locales/en-US/list.json, public/locales/zh-CN/list.json, styles/globals.css, utils/hooks.tsx
1. add block from/to filters in tx list of an account
2. add address from/to filters in transfer list of a tx
Ref: https://github.com/Magickbase/godwoken_explorer/issues/556
---
https://user-images.githubusercontent.com/7271329/174867302-1b9fba35-6770-462e-b32c-29c2a6d92659.mov
https://user-images.githubusercontent.com/7271329/174867383-cbcda691-4278-4588-ae95-2e75ac5cf873.mov
=> feat: add some filters

components/Logo.tsx
Fix font size of logo version part. Even if user's browser set minimum font-size to 12px, it will still look good
=> fix: logo font size

README.md, components/TruncatedAddress.tsx, styles/globals.css
1. remove capitalizing of name and symbol
2. remove symbol from token list
Ref: nervosnetwork/godwoken-info#41 (comment)
=> feat: update name and symbol of token

components/DownloadMenu/index.tsx, pages/token/[id].tsx
1. recover the download button of holder list
2. fix download url
=> fix: enable downloading holder list

components/Header.tsx, pages/_app.tsx, pages/index.tsx
fix issues reported in: https://github.com/Magickbase/godwoken_explorer/issues/803
=> fix: update UI

styles/globals.scss
This commit updates selection color
- Mainnet：#D8CFF3
- Testnet：#C9E1FE
Ref: https://github.com/Magickbase/godwoken_explorer/issues/851
=> feat: update selection color

components/PageTitle/styles.module.scss, pages/nft-collection/[address].tsx, pages/nft-collection/styles.module.scss, public/locales/en-US/nft.json, public/locales/zh-CN/nft.json
Only `info` and `stats` are implemented
=> feat: add nft collection detail page

components/Header.tsx
hover color on menus in header
=> fix: menu hover color

components/Amount.tsx, components/RoundedAmount.tsx, styles/globals.scss
1. set font weight 500
2. set fraction color #938dac on mainnet
3. set fraction color #8f9fb8 on testnet
Ref: https://github.com/Magickbase/godwoken_explorer/issues/861
=> feat: refine amount style

components/Alert/index.tsx, components/CopyBtn/index.tsx
https://github.com/Magickbase/godwoken_explorer/issues/862, point 2, add alert styles
=> feat: custom alerts

components/NftActivityList/index.tsx, components/NftActivityList/styles.module.scss, pages/nft-collection/[address].tsx
This commit adds a basic layout of nft activity list on nft collection detail page, and will be updated when APIs are ready
=> feat: add nft collection detail page (#421)

components/Header.tsx, pages/index.tsx, styles/globals.scss
fix: 
- https://github.com/Magickbase/godwoken_explorer/issues/874
- https://github.com/Magickbase/godwoken_explorer/issues/878
=> fix: home page content width & scroll bar problem

components/ContractInfo/index.tsx, components/ContractInfo/styles.module.scss
1. add 'pure and view' title in read contract tab
2. add 'call staic' title in read contract tab
3. add 'non-payable and payable' title in write contract tab
Ref: https://github.com/Magickbase/godwoken_explorer/issues/864
=> feat: add title in interaction of contract

components/TxList/index.tsx, components/TxList/styles.module.scss
All tx list: https://godwoken-explorer-ui-git-display-method-nervosnet.vercel.app/txs
Tx List of a block: https://godwoken-explorer-ui-git-display-method-nervosnet.vercel.app/block/0x62034ba12a9c744b812c12e1c54083bd1b082f0feb50dbe9b863063478c0362c
Tx List of an account: https://godwoken-explorer-ui-git-display-method-nervosnet.vercel.app/account/0x1cb9c569d3f9682a685ef32371b6cfea2a738b51
Ref: https://github.com/Magickbase/godwoken_explorer/issues/762
=> feat: add method field in tx list

components/ContractEventListItem.tsx, components/ContractEventsList.tsx, components/Layout.tsx, pages/blocks.tsx, pages/charts.tsx, pages/contracts.tsx, pages/index.tsx, pages/tokens/[type].tsx, pages/txs/index.tsx, styles/mixin.scss
fixes https://github.com/Magickbase/godwoken_explorer/issues/946
fixes https://github.com/Magickbase/godwoken_explorer/issues/948
fixes https://github.com/Magickbase/godwoken_explorer/issues/947
=> fix: ui bugs

components/Alert/index.tsx
fixes: https://github.com/Magickbase/godwoken_explorer/issues/909
https://user-images.githubusercontent.com/32790369/190860092-98d257d5-5ae6-4ea2-bcfe-585d8e3f8241.mov
=> fix: mui alert component default severity

components/TokenApprovalList/RevokeButton.tsx, public/locales/en-US/list.json, public/locales/zh-CN/list.json
resolves: https://github.com/Magickbase/godwoken_explorer/issues/1106
Fix after switch network wagmi do not invoke metatmask to send tx problem
https://user-images.githubusercontent.com/32790369/198861135-4e055521-142b-451c-9f3c-44cc062b8f24.mov
**Note**: there could be a delay after confirming switch network and before invoking send tx page (because there is some preparing work wagmi may need to do after network change)
=> fix: revoke button `connect + switch network + send tx` one click flow

pages/multi-token-collection/[address].tsx, pages/multi-token-collection/styles.module.scss, pages/nft-collection/[address].tsx, pages/nft-collection/styles.module.scss, public/locales/en-US/multi-token.json, public/locales/en-US/nft.json, public/locales/zh-CN/multi-token.json, public/locales/zh-CN/nft.json
This PR addes `official site` and `description` on ERC 721/1155 pages
as ERC 20 page did
=> feat: add official site on erc 721/1155 pages

components/AccountOverview/index.tsx, components/AccountOverview/styles.module.scss, components/InfoList/index.tsx, components/InfoList/styles.module.scss, components/SmartContractInfo/index.tsx, components/SmartContractInfo/styles.module.scss
------
There are two points in this issue:
1、Deployer and Deploy Transaction fields are truncated without ellipsis
2、Deploy Transaction label is wrapped
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1150
Check List
------
e2e Test
none
=> Fix: Truncated field misses ellipsis and label is wrapped

pages/token/[id].tsx, pages/token/styles.module.scss, pages/tx/[hash].tsx, pages/tx/styles.module.scss
------
There are two points in this issue:
1、The color of the ellipsis is found to be abnormal in the page of token detail.
2、Data left alignment problem occurs when the Overview of Transaction Info is compatible with the mobile terminal.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1168
Check List
------
e2e Test
none
=> Fix: optimize displayed on the transaction info and token pages.

pages/tokens/[type].tsx, pages/tokens/styles.module.scss
------
This PR is for the page of `Bridge Token` and `Layer 2 Native Token`.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/556
Check List
------
1、sorted by total supply/circulating supply
2、sorted by holders
3、sorted by name
4、filtered by name (fuzzy)
e2e Test
none
=> Feat: change the pagination to cursor and add sorter --- Bridge Token and Layer 2 Native Token

.gitignore, components/Tooltip.tsx, package-lock.json, styles/tooltip.scss
------
Uniform the background color of the tooltip to be `#000000`, and the opacity to be `0.8`.
Figma: https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A1378&t=DaTd93SVt1TYisnq-0
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1216
Check List
------
e2e Test
none
=> Fix: The background color of the tooltip needs to be #000000. 

components/CommonERCTransferlist/index.tsx
------
As Title.
We are losing a parameter to handle this value. 
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1263
Check List
------
e2e Test
none
=> Fix: The value displayed a wrong number in transaction list page.

components/NFTActivityList/index.tsx
------
The Token ID in the page should be unique, and the interface data is normal.
https://v1.testnet.gwscan.com/zh-CN/nft-collection/0xb78e53b2f06e9e1d302ee6e35a482f586d4cc4e3?tab=activity
After:
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1335
Check List
------
e2e Test
none
=> Fix:The tokenid displayed in the active tab is abnormal. 

components/AccountOverview/index.tsx, components/MultiTokenActivityList/index.tsx, components/NFTActivityList/index.tsx, components/TxList/index.tsx, pages/index.tsx
------
As title.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1353
Check List
------
e2e Test
none
=> fix:Some pages are displayed abnormally online.

pages/multi-token-collections/index.tsx, pages/multi-token-collections/styles.module.scss, utils/handler.ts
------
This PR is for the page of `Multi-collections`.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/556
Check List
------
1、sorted by total supply/circulating supply
2、sorted by holders
3、sorted by name
4、filtered by name (fuzzy)
e2e Test
none
=> Feat: change the pagination to cursor and add sorter --- Multi collections 

components/TruncatedAddress.tsx
------
As title.
https://user-images.githubusercontent.com/22511289/234490625-d3b865eb-0e54-49dc-b0ba-13410888fc6d.mp4
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1417
Check List
------
e2e Test
none
=> fix: user account add zero address link jump

components/MultiTokenActivityList/index.tsx, components/NFTActivityList/index.tsx
------
As title.
Ref: https://github.com/Magickbase/godwoken_explorer/issues/1398
Check List
------
e2e Test
none
=> fix: cannot read properties in multi-token page
